accent = "#99aacc"
cursor = "#deeeed"
foreground = "#deeeed"
background = "#101010"
selection_foreground = "#101010"
selection_background = "#deeeed"
color0 = "#000000"
color1 = "#D70000"
color2 = "#789978"
color3 = "#abab77"
color4 = "#7788AA"
color5 = "#708090"
color6 = "#deeeed"
color7 = "#aaaaaa"
color8 = "#555555"
color9 = "#ff8888"
color10 = "#99bb99"
color11 = "#d0d090"
color12 = "#99aacc"
color13 = "#8a9aaa"
color14 = "#ffffff"
color15 = "#DDDDDD"
