# Control your input devices
# See https://wiki.hypr.land/Configuring/Variables/#input
input {
  # Use multiple keyboard layouts and switch between them with Left Alt + Right Alt
  # kb_layout = us,dk,eu

  # Change speed of keyboard repeat
  repeat_rate = 40
  repeat_delay = 600

  # Start with numlock on by default
  numlock_by_default = true

  # Increase sensitivity for mouse/trackpad (default: 0)
  # sensitivity = 0.35

  touchpad {
    # Use natural (inverse) scrolling
    # natural_scroll = true
    #clickfinger_behavior = true 

    # Control the speed of your scrolling
    scroll_factor = 0.1

    # Enable the touchpad while typing
    disable_while_typing = true
    clickfinger_behavior = yes

    # Left-click-and-drag with three fingers
#    drag_3fg = 1
  }
follow_mouse = 1
}

device {
    name = apple-mtp-multi-touch
    disable_while_typing = true
    #enabled = false
}
# Scroll nicely in the terminal
windowrule = scroll_touchpad 1.5, match:class (Alacritty|kitty)
windowrule = scroll_touchpad 0.2, match:class com.mitchellh.ghostty
windowrule = size 150% 150%
bind = SUPER, XF86MonBrightnessUp, exec, brightnessctl -d kbd_backlight s +20
bind = SUPER, XF86MonBrightnessDown, exec, brightnessctl -d kbd_backlight s 20-

    
  

# Enable touchpad gestures for changing workspaces
# See https://wiki.hyprland.org/Configuring/Gestures/sdfasdfasdfasdfsadfsadf
# gesture = 3, horizontal, workspace
